// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl479D2JjWaNdg48ldwH10pAHMKLoz3_4',
    appId: '1:460186603625:web:4d8d99782c69af5cd252f8',
    messagingSenderId: '460186603625',
    projectId: 'yeni-firebase',
    authDomain: 'yeni-firebase.firebaseapp.com',
    storageBucket: 'yeni-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUKoftbL9u6ZKs_EdVD4veqvm8NVmm-Sg',
    appId: '1:460186603625:android:838cc35336a2db10d252f8',
    messagingSenderId: '460186603625',
    projectId: 'yeni-firebase',
    storageBucket: 'yeni-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzOHFMPQDb7to4UI-mFBGBt_NombeljmE',
    appId: '1:460186603625:ios:0401c69f70625f26d252f8',
    messagingSenderId: '460186603625',
    projectId: 'yeni-firebase',
    storageBucket: 'yeni-firebase.firebasestorage.app',
    iosBundleId: 'com.example.memidleTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzOHFMPQDb7to4UI-mFBGBt_NombeljmE',
    appId: '1:460186603625:ios:0401c69f70625f26d252f8',
    messagingSenderId: '460186603625',
    projectId: 'yeni-firebase',
    storageBucket: 'yeni-firebase.firebasestorage.app',
    iosBundleId: 'com.example.memidleTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl479D2JjWaNdg48ldwH10pAHMKLoz3_4',
    appId: '1:460186603625:web:985832b0f6bf5b69d252f8',
    messagingSenderId: '460186603625',
    projectId: 'yeni-firebase',
    authDomain: 'yeni-firebase.firebaseapp.com',
    storageBucket: 'yeni-firebase.firebasestorage.app',
  );
}
